<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header"><?php echo $this->translate("Welcome,"); ?> <?php echo $this->identity->user->getFirstName() . ' ' . $this->identity->user->getLastName(); ?></li>
        <li<?php if($this->leftMenuIndex == 0) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-dashboard'); ?>"><i class="icon-home"></i> <?php echo $this->translate("Dashboard"); ?> <?php if ($this->identity->role == Entities\User::TYPE_USER && $this->total['dashboard'] > 0) {?> <span class="badge badge-info pull-right"><?php echo $this->total['dashboard']; ?></span><?php } ?></a>
        </li>
        <?php if ($this->identity->role == Entities\User::TYPE_USER) { ?>
        <li<?php if($this->leftMenuIndex == 1) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-user-result'); ?>"><i class="icon-eye-open"></i> <?php echo $this->translate("Results"); ?> <?php if ($this->total['result'] > 0) { ?><span class="badge badge-info pull-right"><?php echo $this->total['result']; ?></span><?php } ?></a>
        </li>
        <?php } else if ($this->identity->role == Entities\User::TYPE_ADMIN) { ?>
        <!--<li<?php if($this->leftMenuIndex == 7) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-notification-index'); ?>"><i class="icon-info-sign"></i> <?php echo $this->translate("Notifications"); ?> <span class="badge badge-info pull-right">3</span></a>
        </li>-->
        <?php } ?>
        <li<?php if($this->leftMenuIndex == 2) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-user-edit'); ?>"><i class="icon-asterisk"></i> <?php echo $this->translate("Profile information"); ?></a>
        </li>
        <!--<li><a href="#"><i class="icon-bookmark"></i> <?php echo $this->translate("Knowledge center"); ?></a></li>-->
        <?php if ($this->identity->role != Entities\User::TYPE_USER) { ?>
        <li class="nav-header"><?php echo $this->translate("Administration"); ?></li>
        <li<?php if($this->leftMenuIndex == 3) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-user-index'); ?>"><i class="icon-user"></i> <?php echo $this->translate("User"); ?> <span class="badge pull-right"><?php echo $this->total['user']; ?></span></a>
        </li>
        <li<?php if($this->leftMenuIndex == 4) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-project-index'); ?>"><i class="icon-book"></i> <?php echo $this->translate("Project"); ?> <span class="badge pull-right"><?php echo $this->total['project']; ?></span></a>
        </li>
        <?php if ($this->identity->role == Entities\User::TYPE_SUPER_ADMIN) { ?>
        <li<?php if($this->leftMenuIndex == 5) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-scenario-index'); ?>"><i class="icon-list"></i> <?php echo $this->translate("Scenario"); ?> <span class="badge pull-right"><?php echo $this->total['scenario']; ?></span></a>
        </li>
        <li<?php if($this->leftMenuIndex == 6) echo ' class="active"'; ?>>
            <a href="<?php echo $this->routeUrl('cloud-assessment-index'); ?>"><i class="icon-tags"></i> <?php echo $this->translate("Assessment category"); ?> <span class="badge pull-right"><?php echo $this->total['assessment']; ?></span></a>
        </li>
        <?php } ?>
        <?php } ?>
        <li class="nav-header">&nbsp;</li>
        <li><a href="<?php echo $this->routeUrl('cloud-logout'); ?>"><i class="icon-off"></i> <?php echo $this->translate("Sign out"); ?></a></li>
    </ul>
</div>