<div class="row">
    <div class="span9">
        <?php echo $this->breadcrumb($this->params); ?>
        <?php echo $this->alert($this->messages); ?>
        <?php echo $this->alert($this->flashMessages); ?>
        <div class="row">
            <a href="<?php echo $this->routeUrl('cloud-assessment-create'); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> <?php echo $this->translate('Create new assessment category'); ?></a>
        </div>
        <?php if (sizeof($this->assessmentCategoryPaginator) > 0) { ?>
        <ul class="nav nav-tabs" id="categoryTab">
        <?php foreach($this->assessmentCategoryPaginator->getCurrentItems() as $index => $assessmentCategory) { ?>
            <li <?php if($index == 0) { echo 'class="active"'; } ?>>
                <a href="#<?php echo 'categoryTab_' . $assessmentCategory->getId(); ?>"><?php echo $assessmentCategory->getName(); ?></a>
            </li>
        <?php } ?>
            <li><a href="#categoryTab_add"><i class="icon-plus"></i> <span style="color: #666;"><?php echo $this->translate("Add tab"); ?></span></a></li>
        </ul>
        <div class="tab-content">
        <?php foreach($this->assessmentCategoryPaginator->getCurrentItems() as $index => $assessmentCategory) { ?>
            <div class="tab-pane <?php if($index == 0) { echo 'active'; } ?>" id="<?php echo 'categoryTab_' . $assessmentCategory->getId(); ?>">
                <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th><?php echo $this->translate("Name"); ?></th>
                        <th><?php echo $this->translate("Description"); ?></th>
                        <th><?php echo $this->translate("Parent Category"); ?></th>
                        <th><?php echo $this->translate("Action"); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $this->loopIndex = 0; ?>
                    <?php echo $this->printCategories($assessmentCategory); ?>
                </tbody>
                </table>
            </div>
        <?php } ?>
            <div class="tab-pane" id="categoryTab_add">
                <?php echo $this->form; ?>
            </div>
        </div>

        <script type="text/javascript">
            $(function () {
                $('#categoryTab a').click(function (e) {
                    e.preventDefault();
                    $(this).tab('show');
                })

                $('.btn-remove').click(function(e){
                    var response = confirm("<?php echo $this->translate('Are you sure you want to delete this object?'); ?>");
                    return response;
                });
            });

        </script>
        <?php } ?>
    </div>
</div>