<div class="row">
    <div class="span9">
        <?php echo $this->breadcrumb($this->params); ?>
        <?php echo $this->alert($this->messages); ?>
        <?php echo $this->alert($this->flashMessages); ?>

        <div class="well well-small">
            <h4><?php echo $this->scenario->getTitle(); ?></h4>
            <p><?php echo $this->scenario->getDescription(); ?></p>
        </div>

        <ul class="nav nav-tabs" id="scenarioTab">
            <li class="active"><a href="#scenarioTabSection"><?php echo $this->translate("Sections"); ?></a></li>
            <li><a href="#scenarioTabQuestion"><?php echo $this->translate("Questions"); ?></a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="scenarioTabSection">
                <div class="row">
                    <a href="<?php echo $this->routeUrl('cloud-scenario-section-create', $this->params); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> <?php echo $this->translate('Add new section'); ?></a>
                </div>
                <?php if (sizeof($this->scenario->getSections()) > 0) { ?>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><?php echo $this->translate("Title"); ?></th>
                            <th><?php echo $this->translate("Information"); ?></th>
                            <th><?php echo $this->translate("# of elements"); ?></th>
                            <th><?php echo $this->translate("Action"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->scenario->getSections() as $index => $section) { ?>
                        <tr>
                            <td><?php echo $section->getSequence(); ?></td>
                            <td style="max-width: 300px;"><?php echo $section->getTitle(); ?></td>
                            <td style="max-width: 300px;"><?php echo $section->getDescription(); ?></td>
                            <td style="text-align: center;"><?php echo sizeof($section->getElements()); ?></td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?php echo $this->routeUrl('cloud-scenario-section-edit', array('id' => $section->getId())); ?>" class="btn"><i class="icon-edit"></i></a>
                                    <a href="<?php echo $this->routeUrl('cloud-scenario-section-delete', array('id' => $section->getId())); ?>" class="btn btn-remove"><i class="icon-remove"></i></a>
                                </div>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                <?php } ?>
            </div>
            <div class="tab-pane" id="scenarioTabQuestion">
                <div class="row">
                    <a href="<?php echo $this->routeUrl('cloud-scenario-question-create', $this->params); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> <?php echo $this->translate('Add new question'); ?></a>
                </div>
                <?php if (sizeof($this->scenario->getElements()) > 0) { ?>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th><?php echo $this->translate("Text"); ?></th>
                            <th><?php echo $this->translate("Section"); ?></th>
                            <th><?php echo $this->translate("Type"); ?></th>
                            <th><?php echo $this->translate("Action"); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->scenario->getElements() as $index => $element) { ?>
                        <tr>
                            <td><?php echo $index+1; ?></td>
                            <td style="max-width:380px;"><?php echo $element->getLabel(); ?></td>
                            <td><?php echo $element->getSection()->getTitle(); ?></td>
                            <td><?php echo ucwords($element->getType()); ?></td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?php echo $this->routeUrl('cloud-scenario-question-edit', array('id' => $element->getId())); ?>" class="btn"><i class="icon-edit"></i></a>
                                    <a href="<?php echo $this->routeUrl('cloud-scenario-question-delete', array('id' => $element->getId())); ?>" class="btn btn-remove"><i class="icon-remove"></i></a>
                                </div>
                            </td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                <?php } ?>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#scenarioTab a').click(function (e) {
                    e.preventDefault();
                    $(this).tab('show');
                })

                $('.btn-remove').click(function(e){
                    var response = confirm("<?php echo $this->translate('Are you sure you want to delete this object?'); ?>");
                    return response;
                });
            });
        </script>

    </div>
</div>