<div class="row">
    <div class="span9">
        <?php echo $this->breadcrumb($this->params); ?>
        <?php echo $this->alert($this->flashMessages); ?>
        <div class="row">
            <a href="<?php echo $this->routeUrl('cloud-scenario-create'); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> <?php echo $this->translate('Create new scenario'); ?></a>
        </div>
        <?php if (sizeof($this->scenarioPaginator) > 0) { ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate("Title"); ?></th>
                    <th><?php echo $this->translate("# of sections"); ?></th>
                    <th><?php echo $this->translate("# of elements"); ?></th>
                    <th><?php echo $this->translate("Action"); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->scenarioPaginator->getCurrentItems() as $index => $scenario) { ?>
                <tr>
                    <td><?php echo $index+1; ?></td>
                    <td><?php echo $scenario->getTitle(); ?></td>
                    <td style="text-align: center;"><?php echo sizeof($scenario->getSections()); ?></td>
                    <td style="text-align: center;"><?php echo sizeof($scenario->getElements()); ?></td>
                    <td>
                        <div class="btn-group">
                            <a href="<?php echo $this->routeUrl('cloud-scenario-edit', array('id' => $scenario->getId())); ?>" class="btn"><i class="icon-edit"></i></a>
                            <a href="<?php echo $this->routeUrl('cloud-scenario-detail', array('id' => $scenario->getId())); ?>" class="btn"><i class="icon-info-sign"></i></a>
                            <a href="<?php echo $this->routeUrl('cloud-scenario-delete', array('id' => $scenario->getId())); ?>" class="btn btn-remove"><i class="icon-remove"></i></a>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <script type="text/javascript">
            $('.btn-remove').click(function(e){
                var response = confirm("<?php echo $this->translate('Are you sure you want to delete this object?'); ?>");
                return response;
            });
        </script>
        <?php } ?>
    </div>
</div>