<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Subgroup &middot; C-FAR System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="/assets/plugins/jqueryui/1.10.1/css/smoothness/jquery-ui-1.10.1.custom.min.css" rel="stylesheet" />
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
      .main-content {
        min-height: 600px;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="/assets/ico/favicon.ico">

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="/assets/js/highcharts/3.0/highcharts.js"></script>
    <script src="/assets/js/highcharts/3.0/highcharts-more.js"></script>
    <script src="/assets/js/highcharts/3.0/modules/exporting.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/plugins/jqueryui/1.10.1/js/jquery-ui-1.10.1.custom.min.js"></script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/"><img src="/assets/img/STS-S.png" style="float: left; display: inline; height: 24px;"/> <b style="float: left; display: inline; margin-top: 4px; margin-left: 6px;">C-FAR System</b> <span style="float: left; display: inline; font-size: 12px; margin-top: 6px; margin-left: 4px;">version 0.9.2a</span></a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right" style="margin-top: 6px;">

            </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row main-content">
        <div class="span3">
          <?php echo $this->action('index', 'menu', null, $this->params); ?>
        </div>
        <div class="span9">
          <?php echo $this->layout()->content; ?>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Subgroup Consulting AB 2013</p>
        <p>Memory footprint: <?php echo sprintf("%.2f MBytes", memory_get_peak_usage()/(1024*1024));  ?></p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


  </body>
</html>
