<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Invitation
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Invitation extends EntityRepository
{

    public function getPercentageAnsweredRequiredElementByInvitation($invitation)
    {
        // get total required elements
        $requiredElements = $this->_em->getRepository('Entities\Scenario\Element')
            ->getRequiredElementsByScenario($invitation->getScenario());

        // get required element ids
        $requiredElementIds = array();
        foreach($requiredElements as $requiredElement) {
            $requiredElementIds[] = $requiredElement->getId();
        }

        // get answers for the current invitation
        $answers = $invitation->getAnswers();
        $counter = 0;
        foreach($answers as $answer) {
            if(in_array($answer->getElement()->getId(), $requiredElementIds)) {
                $counter += 1;
            }
        }

        return (sizeof($requiredElementIds) > 0) ? round($counter/sizeof($requiredElementIds) * 100) : 0;
    }
}