<div class="row">
    <div class="span9">
        <?php echo $this->breadcrumb($this->params); ?>
        <?php echo $this->alert($this->messages); ?>
        <div class="row">
            <a href="<?php echo $this->routeUrl('cloud-user-create'); ?>" class="btn btn-primary pull-right"><i class="icon-plus icon-white"></i> <?php echo $this->translate('Add new user'); ?></a>
        </div>
        <?php if (sizeof($this->userPaginator) > 0) { ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate("Username"); ?></th>
                    <th><?php echo $this->translate("First Name"); ?></th>
                    <th><?php echo $this->translate("Last Name"); ?></th>
                    <th><?php echo $this->translate("Type"); ?></th>
                    <th><?php echo $this->translate("# of projects"); ?></th>
                    <th><?php echo $this->translate("Action"); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->userPaginator->getCurrentItems() as $index => $user) { ?>
                <tr>
                    <td><?php echo $index+1; ?></td>
                    <td><?php echo $user->getEmail(); ?></td>
                    <td><?php echo $user->getFirstName(); ?></td>
                    <td><?php echo $user->getLastName(); ?></td>
                    <td style="text-align: center;"><?php echo $user->getType(); ?></td>
                    <td style="text-align: center;"><?php echo sizeof($user->getInvitations()); ?></td>
                    <td>
                        <div class="btn-group">
                          <a href="<?php echo $this->routeUrl('cloud-user-edit', array('id' => $user->getId())); ?>" class="btn"><i class="icon-edit"></i></a>
                          <?php if($user->getType() == Entities\User::TYPE_USER) { ?>
                          <a href="<?php echo $this->routeUrl('cloud-user-detail', array('id' => $user->getId())); ?>" class="btn"><i class="icon-info-sign"></i></a>
                          <a href="<?php echo $this->routeUrl('cloud-user-delete', array('id' => $user->getId())); ?>" class="btn btn-remove"><i class="icon-remove"></i></a>
                          <?php } ?>
                        </div>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
        <script type="text/javascript">
            $('.btn-remove').click(function(e){
                var response = confirm("<?php echo $this->translate('Are you sure you want to delete this object?'); ?>");
                return response;
            });
        </script>
        <?php } ?>
    </div>
</div>